apiVersion: v1
kind: Pod
metadata:
  name: busybox-env
  labels:
    app: busybox

spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ["sh", "-c", "env"]
      envFrom:
        - configMapRef:
            name: app-config
  restartPolicy: Never