apiVersion: v1
kind: Pod
metadata:
  name: pvc-dynamic-pod
spec:
  containers:
  - name: writer
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          echo "Dynamic Pod $(hostname) wrote at $(date)" >> /data/message.txt;
          sleep 10;
        done
    volumeMounts:
    - name: data-volume
      mountPath: /data
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: pvc-dynamic-demo
